### ISSUE TITLE
How to run mqt-qecc on google colab

### ISSUE THREAD

**Issue by hardik954** [cda-tum/mqt-qecc#224]
### Discussed in https://github.com/cda-tum/mqt-qecc/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **hardik954** May  5, 2024</sup>
I want to run the "[test_analog_tannergraph_decoding.py] present in the test.python.analog_info in GOOGLE COLAB folder but how do I do it? I have cloned the repo installed all the requirements yet i can't do it. Can someone please help me
</div>

**Comment by burgholzer** [comment]
Closing this, as it is not really an issue and you already started a discussion, which is the proper place to discuss things like this 😌
